sudo: false
language: java
install: mvn package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "JGNrQ4XoozGBpzSIs2IUiONEJCzUSzr5xsCmvwslKCe45IU619lKbU2wMRGBXML6OEm59MWJNw/QUt2s5O7uXIysXZ+ROyis3pOzQCZ57BIyl4dEhejD0K5Jy956i9U0kEJvKpbsGfiQg33uMD4HVeaZwwzbMEA/1lqAgXRzvS/vX776woSgyImmwxB8W3EBVKxRfoMRunt6ynmXVXDEGrw87RHeq+Kj6E0r5NG9teBiWxHyrkyY9HLeybL297uhgMO2f8c22gpEHYKOzmumk7w6yqj3tHXSTEvjE3iLHRHma4ruJMim6a6r5rz8k5zLzwAUY5OyYsN1OQQ41/uat9PrVStle+Krt/3GjSeWKyfiIYggPzexvHJTUbYdwVXeLEyz/cODqqWnSAJJ8wUS3kzH/4tyL0x4y6vQ2n//3NJgY8AKe5TyQMX1ceTJianIn8VILlVIj5kwgfeemoxARIwjFE295VBcm9BmiDgxsfkYVjdCw6skRvlT/8FeRCoLrPL2brSdI4ty45qPl89b5jdi37KKWyYV+WLqeB4p99QIZ/xTc+ANMt1x1uDRF4Pn/rCQfDCoehsFHThFdfwtgn8t/PhBtJzSsuAiNv6YQI+pjKfvSMcvbCCLv7zoir2BypCBJJhBln8X4cIDsz2+7JCn95X0tarFe0ObnyHttUE="
  file: "target/Dozer.jar"